[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#1d4ed8"
backgroundColor = "#f4f7fe"
secondaryBackgroundColor = "#ffffff"
textColor = "#0c1535"
font = "sans serif"
